name: bebi_app
description: "A Flutter app designed for couples to stay connected through cycle tracking, shared calendars, daily stories, and location sharing."
publish_to: "none"
version: 0.3.3

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">= 3.35.2"

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_ai: ^3.1.0
  firebase_analytics: ^12.0.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_remote_config: ^6.0.0
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_keyboard_visibility_temp_fork: ^0.1.5
  flutter_localizations:
    sdk: flutter
  flutter_markdown_plus: ^1.0.3
  flutter_refresh_rate_control: ^0.0.4+1
  get_it: ^8.2.0
  go_router: ^16.1.0
  hive_ce_flutter: ^2.3.1
  image_picker: ^1.1.2
  injectable: ^2.5.1
  intl: ^0.20.2
  material_symbols_icons: ^4.2815.1
  package_info_plus: ^8.3.1
  paged_vertical_calendar: ^1.1.10
  sentry_flutter: ^9.6.0
  skeletonizer: ^2.1.0+1
  super_editor: ^0.3.0-dev.29
  super_editor_markdown: ^0.2.0
  table_calendar: ^3.2.0
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.6.0
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.1
  injectable_generator: ^2.8.1
  sentry_dart_plugin: ^3.1.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_logo/app_logo.png
    - assets/fonts/ibm_plex_sans/
    - assets/fonts/vidaloka/
  fonts:
    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/ibm_plex_mono/IBMPlexMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/ibm_plex_mono/IBMPlexMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/ibm_plex_mono/IBMPlexMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ibm_plex_mono/IBMPlexMono-Bold.ttf
          weight: 700
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-Bold.ttf
          weight: 700
    - family: Vidaloka
      fonts:
        - asset: assets/fonts/vidaloka/Vidaloka-Regular.ttf
          weight: 400

flutter_native_splash:
  color: "#F5F6F7"
  image: "assets/app_logo/app_logo.png"
  android_12:
    color: "#F5F6F7"
    image: "assets/app_logo/app_logo_android12.png"

icons_launcher:
  platforms:
    web:
      enable: true
      image_path: "assets/app_logo/app_logo.png"
    android:
      enable: true
      image_path: "assets/app_logo/app_logo_android12.png"
      adaptive_foreground_image: "assets/app_logo/app_logo_android12.png"
      adaptive_background_color: "#F5F6F7"
    ios:
      enable: true
      image_path: "assets/app_logo/app_logo_ios.png"

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: bebi-app-flutter
  org: personal-projects-organization
