name: Crashlytics Upload

env: {}

inputs:
  token:
    description: Firebase CI token
    required: true
  app_id:
    description: Firebase app id
    required: true
  symbols_path:
    description: Path to the symbols directory
    required: true

runs:
  using: composite
  steps:
    - name: Upload debug symbols to Firebase Crashlytics
      shell: bash
      run: |
        firebase crashlytics:symbols:upload \
          --token=${{ inputs.token }} \
          --app=${{ inputs.app_id }} \
          ${{ inputs.symbols_path }}