name: Rename Artifacts

inputs:
  platform:
    description: android or ios
    required: true

runs:
  using: composite
  steps:
    - name: Rename Android APKs
      if: ${{ inputs.platform == 'android' }}
      shell: bash
      run: |
        cd build/app/outputs/flutter-apk
        mv app-arm64-v8a-release.apk android_modern_devices.apk
        mv app-armeabi-v7a-release.apk android_older_devices.apk
        mv app-x86_64-release.apk android_emulator.apk
    - name: Rename iOS IPA
      if: ${{ inputs.platform == 'ios' }}
      shell: bash
      run: |
        cd build/ios/iphoneos
        mv app.ipa ios.ipa