name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: "Build number (optional, defaults to run number)"
        required: false
        type: string
  workflow_call:
    inputs:
      build_number:
        required: false
        type: string

jobs:
  build-android:
    name: Build APK
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Prepare Flutter project
        uses: ./.github/actions/flutter-prepare
        with:
          flutter_version: 3.35.2
          firebase_project: bebi-app
          firebase_token: ${{ secrets.FIREBASE_CI_TOKEN }}
          firebase_platforms: android
          out_path: lib/config/firebase_options.dart
          generate_l10n: "true"

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            android/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Configure environment
        run: echo "${{ secrets.ENVIRONMENT }}" | base64 --decode > .env

      - name: Set build number
        id: build_number
        run: |
          if [ -n "${{ inputs.build_number }}" ]; then
            echo "number=${{ inputs.build_number }}" >> $GITHUB_OUTPUT
          elif [ -n "${{ github.event.inputs.build_number }}" ]; then
            echo "number=${{ github.event.inputs.build_number }}" >> $GITHUB_OUTPUT
          else
            echo "number=${{ github.run_number }}" >> $GITHUB_OUTPUT
          fi

      - name: Build Android
        run: |
          flutter build apk \
          --release \
          --obfuscate \
          --split-debug-info=build/app/outputs/symbols \
          --build-number=${{ steps.build_number.outputs.number }} \
          --split-per-abi

      - name: Rename APK files with user-friendly names
        uses: ./.github/actions/rename-artifacts
        with:
          platform: android

      - name: Upload debug symbols to Sentry
        uses: ./.github/actions/sentry-upload
        with:
          sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Upload Android build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: build/app/outputs/flutter-apk/*.apk
