name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: "Build number (optional, defaults to run number)"
        required: false
        type: string
  workflow_call:
    inputs:
      build_number:
        required: false
        type: string

jobs:
  build-android:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Prepare Flutter project
        uses: ./.github/actions/flutter-prepare
        with:
          flutter_version: 3.35.5
          firebase_project: bebi-app
          firebase_token: ${{ secrets.FIREBASE_CI_TOKEN }}
          firebase_platforms: android

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            android/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Set build number
        id: build_number
        run: |
          if [ -n "${{ inputs.build_number }}" ]; then
            echo "number=${{ inputs.build_number }}" >> $GITHUB_OUTPUT
          elif [ -n "${{ github.event.inputs.build_number }}" ]; then
            echo "number=${{ github.event.inputs.build_number }}" >> $GITHUB_OUTPUT
          else
            echo "number=${{ github.run_number }}" >> $GITHUB_OUTPUT
          fi

      - name: Create keystore and key.properties
        run: |
          echo "${{ secrets.KEYSTORE_JKS_BASE64 }}" | base64 --decode > android/app/keystore.jks
          echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      - name: Build Android
        run: |
          flutter build apk \
          --release \
          --obfuscate \
          --split-debug-info=build/app/outputs/native-debug-symbols \
          --build-number=${{ steps.build_number.outputs.number }} \
          --split-per-abi

      - name: Upload debug symbols to Crashlytics
        run: |
          echo "Diagnostics: listing build/app/outputs"
          ls -la build/app/outputs || true
          echo "Diagnostics: listing build/app/outputs/symbols"
          ls -la build/app/outputs/symbols || true

          # Prefer new Flutter symbol output dir if present, otherwise fall back.
          if [ -d build/app/outputs/symbols ] && [ "$(ls -A build/app/outputs/symbols)" ]; then
            SYMBOL_DIR=build/app/outputs/symbols
          elif [ -d build/app/outputs/native-debug-symbols ] && [ "$(ls -A build/app/outputs/native-debug-symbols)" ]; then
            SYMBOL_DIR=build/app/outputs/native-debug-symbols
          else
            SYMBOL_DIR=
          fi

          if [ -n "$SYMBOL_DIR" ]; then
            echo "Found symbols in $SYMBOL_DIR, uploading to Crashlytics..."
            ls -la "$SYMBOL_DIR" || true
            firebase crashlytics:symbols:upload \
              --app=${{ secrets.FIREBASE_ANDROID_APP_ID }} \
              "$SYMBOL_DIR"
          else
            echo "ERROR: No symbol directory found. Tried both build/app/outputs/symbols and build/app/outputs/native-debug-symbols."
            echo "Diagnostics above show the current build/app/outputs contents. Ensure Flutter's --split-debug-info was used and the build produced symbol files." 
            exit 1
          fi

      - name: Rename APK files with user-friendly names
        uses: ./.github/actions/rename-artifacts
        with:
          platform: android

      - name: Upload Android build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: build/app/outputs/flutter-apk/*.apk
