name: Deploy to Firebase

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Build and Deploy to Firebase
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      actions: read
    steps:
      - uses: actions/checkout@v4

      - name: Create firebase.json
        run: echo '${{ secrets.FIREBASE_JSON }}' > firebase.json

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.35.2 # Must be the same with the one in pubspec.yaml

      - name: Configure firebase
        run: |
          curl -sL https://firebase.tools | bash
          firebase experiments:enable webframeworks
          dart pub global activate flutterfire_cli
          flutterfire configure \
            --project=bebi-app \
            --platforms=web \
            --token=${{ secrets.FIREBASE_CI_TOKEN }} \
            --out=lib/config/firebase_options.dart \
            --yes

      - name: Download dependencies
        run: flutter pub get

      - name: Run build runner and generate localization files
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter gen-l10n

      - name: Configure firebase.json
        run: echo '${{ secrets.FIREBASE_JSON }}' > firebase.json

      - name: Build Web
        run: flutter build web --release --wasm --build-number=${{ github.run_number }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BEBI_APP }}
          projectId: awesome-period-tracker
          channelId: live
