name: Create release
on:
  workflow_dispatch:
    inputs:
      build_android:
        description: "Build Android APK"
        required: true
        default: true
        type: boolean
      build_ios:
        description: "Build iOS IPA"
        required: true
        default: true
        type: boolean
  push:
    tags:
      - "*"

jobs:
  build-android:
    name: Build APK
    runs-on: ubuntu-24.04
    if: ${{ github.event.inputs.build_android == 'true' || github.event_name != 'workflow_dispatch' }}
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.35.1 # Must be the same with the one in pubspec.yaml
          cache: true

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: flutter-deps-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            flutter-deps-${{ runner.os }}-

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            android/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Configure environment
        run: echo "${{ secrets.ENVIRONMENT }}" | base64 --decode > .env

      - name: Cache Firebase CLI and global packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/firebase
            ~/.pub-cache/bin
            ~/.pub-cache/global_packages
          key: firebase-cli-${{ runner.os }}-v1
          restore-keys: |
            firebase-cli-${{ runner.os }}-

      - name: Configure firebase
        run: |
          if ! command -v firebase &> /dev/null; then
            curl -sL https://firebase.tools | bash
          fi
          if ! dart pub global list | grep -q flutterfire_cli; then
            dart pub global activate flutterfire_cli
          fi
          export PATH="$PATH":"${{ runner.tool_cache }}/flutter/stable-3.35.1/bin"
          flutterfire configure \
            --project=bebi-app \
            --platforms=android \
            --token=${{ secrets.FIREBASE_CI_TOKEN }} \
            --out=lib/config/firebase_options.dart \
            --yes

      - name: Download dependencies
        run: flutter pub get

      - name: Run build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Android
        run: flutter build apk --release --obfuscate --split-debug-info=build/app/outputs/symbols --build-number=${{ github.run_number }} --split-per-abi

      - name: Rename APK files with user-friendly names
        run: |
          cd build/app/outputs/flutter-apk
          mv app-arm64-v8a-release.apk "android_modern_devices.apk"
          mv app-armeabi-v7a-release.apk "android_older_devices.apk"
          mv app-x86_64-release.apk "android_emulator.apk"

      - name: Upload debug symbols to Firebase Crashlytics
        run: |
          firebase crashlytics:symbols:upload \
            --token=${{ secrets.FIREBASE_CI_TOKEN }} \
            --app=${{ secrets.FIREBASE_ANDROID_APP_ID }} \
            build/app/outputs/symbols

      - name: Upload Android build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: build/app/outputs/flutter-apk/*.apk

  build-ios:
    name: Build IPA
    runs-on: macos-14
    if: ${{ github.event.inputs.build_ios == 'true' || github.event_name != 'workflow_dispatch' }}
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.35.1 # Must be the same with the one in pubspec.yaml
          cache: true

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: flutter-deps-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            flutter-deps-${{ runner.os }}-

      - name: Cache iOS build cache
        uses: actions/cache@v4
        with:
          path: |
            ios/Pods
            ~/.cocoapods
            ~/Library/Caches/CocoaPods
          key: ios-pods-${{ runner.os }}-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ios-pods-${{ runner.os }}-

      - name: Download dependencies
        run: flutter pub get

      - name: Generate build runner files and localizations
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter gen-l10n

      - name: Cache Firebase CLI and global packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/firebase
            ~/.pub-cache/bin
            ~/.pub-cache/global_packages
          key: firebase-cli-${{ runner.os }}-v1
          restore-keys: |
            firebase-cli-${{ runner.os }}-

      - name: Configure firebase
        run: |
          if ! command -v firebase &> /dev/null; then
            curl -sL https://firebase.tools | bash
          fi
          if ! dart pub global list | grep -q flutterfire_cli; then
            dart pub global activate flutterfire_cli
          fi
          export PATH="$PATH":"${{ runner.tool_cache }}/flutter/stable-3.35.1/bin"
          flutterfire configure \
            --project=bebi-app \
            --platforms=ios \
            --token=${{ secrets.FIREBASE_CI_TOKEN }} \
            --out=lib/config/firebase_options.dart \
            --yes

      - name: Build iOS
        run: flutter build ios --release --no-codesign --obfuscate --split-debug-info=build/ios/outputs/symbols --build-number=${{ github.run_number }}

      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r app.ipa Payload

      - name: Rename IPA file with user-friendly name
        run: |
          cd build/ios/iphoneos
          mv app.ipa "ios.ipa"

      - name: Upload iOS build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-artifacts
          path: build/ios/iphoneos/ios.ipa

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-android, build-ios]
    if: |
      always() &&
      (needs.build-android.result == 'success' || needs.build-android.result == 'skipped') &&
      (needs.build-ios.result == 'success' || needs.build-ios.result == 'skipped')
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        continue-on-error: true

      - name: Read latest version from CHANGELOG
        id: changelog
        shell: bash
        run: |
          LATEST_VERSION=$(grep -m1 "^## \[" CHANGELOG.md | sed -E 's/## \[(.*)\].*/\1/')
          if [ -z "$LATEST_VERSION" ]; then
            echo "No version found in CHANGELOG.md"
            exit 1
          fi

          # Extract content between the current and the next version or until the end of the file
          CHANGELOG_CONTENT=$(awk "/^## \[$LATEST_VERSION\]/ {flag=1} /^## \[/ && flag && !/^## \[$LATEST_VERSION\]/ {flag=0} flag {print}" CHANGELOG.md)

          if [ -z "$CHANGELOG_CONTENT" ]; then
            echo "No changelog content found for version $LATEST_VERSION"
            exit 1
          fi

          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo 'content<<EOF' >> $GITHUB_OUTPUT
          echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Determine artifacts to upload
        id: set_artifacts
        shell: bash
        run: |
          ARTIFACTS=""
          if [[ "${{ github.event.inputs.build_android }}" == "true" || "${{ github.event_name }}" != "workflow_dispatch" ]]; then
            ARTIFACTS+="android-artifacts/*.apk"
          fi
          if [[ "${{ github.event.inputs.build_ios }}" == "true" || "${{ github.event_name }}" != "workflow_dispatch" ]]; then
            if [[ -n "$ARTIFACTS" ]]; then
              ARTIFACTS+=",ios-artifacts/*.ipa"
            else
              ARTIFACTS+="ios-artifacts/*.ipa"
            fi
          fi
          echo "artifacts=$ARTIFACTS" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          prerelease: false
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ steps.set_artifacts.outputs.artifacts }}
          body: |
            ${{ steps.changelog.outputs.content }}

            ### Download Guide

            **For Android users:**
            - **android_modern_devices.apk** - Recommended for most Android phones (2017 and newer)
            - **android_older_devices.apk** - For older Android devices (2010-2017)
            - **android_emulator.apk** - For Android emulators and testing

            **For iOS users:**
            - **ios.ipa** - For iOS devices (requires sideloading with developer account and Xcode)

            > [!TIP]
            > Most users should download the "modern-devices" APK for Android.
