name: Run tests

on:
  push:
    branches-ignore:
      - "v*"
    tags-ignore:
      - "v*"
  workflow_dispatch:

jobs:
  verification:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.8 # Must be the same with the one in pubspec.yaml

      - name: Download dependencies
        run: flutter pub get

      - name: Run build runner
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Create firebase options stub
        run: |
          mkdir -p lib/config
          cat > lib/config/firebase_options.dart << 'EOF'
          import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

          class DefaultFirebaseOptions {
            static FirebaseOptions get currentPlatform {
              throw UnimplementedError(
                'Firebase stub for static analysis only - not for runtime use',
              );
            }
          }
          EOF

      - name: Analyze
        run: flutter analyze --no-pub

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Run tests
        run: flutter test --no-pub --test-randomize-ordering-seed random
