name: Run tests

on:
  push:
    branches-ignore:
      - "v*"
    tags-ignore:
      - "v*"
  workflow_dispatch:

jobs:
  verification:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Flutter project
        uses: ./.github/actions/flutter-prepare
        with:
          flutter_version: 3.35.6
          firebase_project: bebi-app
          firebase_platforms: none

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: flutter-deps-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            flutter-deps-${{ runner.os }}-

      - name: Download dependencies
        run: flutter pub get

      - name: Create firebase options stub
        run: |
          mkdir -p lib/config
          cat > lib/config/firebase_options.dart << 'EOF'
          import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

          class DefaultFirebaseOptions {
            static FirebaseOptions get currentPlatform {
              throw UnimplementedError(
                'Firebase stub for static analysis only - not for runtime use',
              );
            }
          }
          EOF

      - name: Analyze
        run: dart analyze

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Run tests
        run: flutter test --no-pub --test-randomize-ordering-seed random
